# Configuration Decap CMS pour Vilas Elec
# Documentation : https://decapcms.org/docs/

# Backend (Git Gateway pour Netlify)
backend:
  name: git-gateway
  branch: main # ou master selon votre branche principale

# Configuration locale pour tester (à commenter en production)
# local_backend: true

# Publication
publish_mode: editorial_workflow # Active le workflow de publication (brouillon → en révision → publié)

# Médias (images, fichiers)
media_folder: "public/images/uploads" # Dossier où seront stockées les images uploadées
public_folder: "/images/uploads"      # Chemin public pour accéder aux images

# Langue de l'interface
locale: 'fr'

# Collections de contenu
collections:
  # ==========================================
  # 1. ARTICLES DE BLOG
  # ==========================================
  - name: "blog"
    label: "📝 Articles de Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string", required: true, hint: "Titre de l'article (60-70 caractères max pour SEO)" }
      - { label: "Description courte", name: "excerpt", widget: "text", required: true, hint: "Description de 150-160 caractères pour SEO et aperçu" }
      - { label: "Image de couverture", name: "image", widget: "image", required: true, hint: "Image principale de l'article (1200x630px recommandé)" }
      - { label: "Catégorie", name: "category", widget: "select", options: ["Conseils", "Domotique", "Rénovation", "Sécurité", "Réglementation", "GREEN'UP"], required: true }
      - { label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true }
      - { label: "Auteur", name: "author", widget: "string", default: "VILAS ELEC" }
      - { label: "Temps de lecture", name: "readTime", widget: "string", default: "5 min", hint: "Ex: '5 min'" }
      - { label: "Brouillon", name: "draft", widget: "boolean", default: false, hint: "Article en brouillon (non publié)" }
      - { label: "Contenu", name: "body", widget: "markdown", required: true }
      - { label: "Mots-clés SEO", name: "keywords", widget: "list", required: false, hint: "Mots-clés pour le référencement" }

  # ==========================================
  # 2. RÉALISATIONS / PORTFOLIO
  # ==========================================
  - name: "realisations"
    label: "🏗️ Réalisations"
    folder: "src/content/realisations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre du projet", name: "title", widget: "string", required: true }
      - { label: "Description courte", name: "excerpt", widget: "text", required: true }
      - { label: "Image principale", name: "image", widget: "image", required: true, hint: "Photo du projet réalisé (800x800px recommandé)" }
      - { label: "Images supplémentaires", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image" }, required: false }
      - { label: "Catégorie", name: "category", widget: "select", options: ["professionnel", "renovation", "domotique", "tableau", "greenup"], required: true }
      - { label: "Lieu", name: "location", widget: "string", default: "Doubs (25)", hint: "Ex: Besançon, Saint-Vit..." }
      - { label: "Date de réalisation", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Description détaillée", name: "body", widget: "markdown", required: true }
      - { label: "Services utilisés", name: "services", widget: "list", required: false, hint: "Ex: Tableau électrique, Domotique, etc." }

  # ==========================================
  # 3. TÉMOIGNAGES CLIENTS
  # ==========================================
  - name: "testimonials"
    label: "💬 Témoignages"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom du client", name: "name", widget: "string", required: true, hint: "Ex: M. Dupont" }
      - { label: "Ville", name: "location", widget: "string", default: "Besançon" }
      - { label: "Note (sur 5)", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, default: 5 }
      - { label: "Témoignage", name: "body", widget: "text", required: true }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }

  # ==========================================
  # 4. PAGES (Configuration des pages fixes)
  # ==========================================
  - name: "pages"
    label: "📄 Pages"
    files:
      # Page d'accueil
      - label: "🏠 Accueil"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - { label: "Titre Hero", name: "heroTitle", widget: "string" }
          - { label: "Sous-titre Hero", name: "heroSubtitle", widget: "text" }
          - { label: "Image Hero", name: "heroImage", widget: "image" }
          - { label: "Texte CTA (bouton)", name: "ctaText", widget: "string", default: "Demander un devis" }
          - { label: "Section Présentation", name: "body", widget: "markdown" }

      # Page À propos
      - label: "👤 À propos"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Contenu", name: "body", widget: "markdown" }

  # ==========================================
  # 5. PARAMÈTRES DU SITE
  # ==========================================
  - name: "settings"
    label: "⚙️ Paramètres"
    files:
      # Informations générales
      - label: "Informations générales"
        name: "general"
        file: "src/content/settings/general.json"
        fields:
          - { label: "Nom de l'entreprise", name: "siteName", widget: "string", default: "VILAS ELEC" }
          - { label: "Slogan", name: "tagline", widget: "string", default: "Électricien Certifié Legrand à Saint-Vit" }
          - { label: "Adresse", name: "address", widget: "string", default: "6 Rue des Joncs, 25410 Saint-Vit" }
          - { label: "Téléphone", name: "phone", widget: "string", default: "06 00 00 00 00" }
          - { label: "Email", name: "email", widget: "string", default: "contact@vilaselec.fr" }
          - label: "Horaires"
            name: "hours"
            widget: "object"
            fields:
              - { label: "Lundi-Vendredi", name: "weekdays", widget: "string", default: "8h-18h" }
              - { label: "Samedi", name: "saturday", widget: "string", default: "9h-12h" }
              - { label: "Dimanche", name: "sunday", widget: "string", default: "Fermé" }
          - label: "Réseaux sociaux"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string", required: false }
              - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
              - { label: "Instagram", name: "instagram", widget: "string", required: false }

      # SEO
      - label: "SEO"
        name: "seo"
        file: "src/content/settings/seo.json"
        fields:
          - { label: "Meta Description", name: "metaDescription", widget: "text", hint: "Description par défaut du site (150-160 caractères)" }
          - { label: "Mots-clés principaux", name: "keywords", widget: "list", hint: "Mots-clés SEO principaux" }
          - { label: "Image de partage par défaut", name: "ogImage", widget: "image", hint: "Image pour les partages sur réseaux sociaux (1200x630px)" }
